### ISSUE TITLE
end_of_anim

### ISSUE THREAD

**Issue by phmalek** [orangeduck/Motion-Matching#10]
Hi,
Looking through the code, as far as I understood, the end of the clip problem has not been handled. Once the animation reaches the end of the clip, `best_index` is set to `-1`, and then `trns_bone_positions` are accessed by this index, which raises the assertion error of `assert(i >= 0 && i < rows)`.

**Comment by orangeduck** [comment]
Unless I'm mistaken, I believe `best_index` will always be overwritten to something valid by `database_search`

**Comment by phmalek** [comment]
You are right, `ln 687 database.h`.
Thanks
