### ISSUE TITLE
How should I modify features.bin

### ISSUE THREAD

**Issue by huang-1030** [orangeduck/Motion-Matching#13]
Thanks again for the open source code, it helped me a lot to understand motion match. 

When I change database.bin, how should I modify the features.bin corresponding to it, or tell me what the 27-dimensional features of features.bin represent.

Thanks.

**Comment by orangeduck** [comment]
You can see how `features.bin` is constructed in `database_build_matching_features` of `database.h`

**Comment by huang-1030** [comment]
> You can see how `features.bin` is constructed in `database_build_matching_features` of `database.h`

Yeah! According to what you said, I successfully generated a new features.bin file, thank you very much.
