### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by phmalek** [orangeduck/Motion-Matching#2]
Could you please add a small tutorial about how to build and use the code?

**Comment by pau1o-hs** [comment]
Hi mate! If you are using Windows:

1. Install raylib (his path should be C:\raylib);
2. Download raygui repo and move it to "C:\raylib\";
3. Run the "C:\raylib\w64devkit\w64devkit.exe" program;
4. When the program opens, go to your orangeduck's Motion-Matching directory, (for example: "cd Documents/Motion-Matching") then type "make all"
5. The executable file of the project will be generated as "controller.exe", just open it.

And there you go :)

**Comment by zztianzz** [comment]
> Hi mate! If you are using Windows:
> 
> 1. Install raylib (his path should be C:\raylib);
> 2. Download raygui repo and move it to "C:\raylib";
> 3. Run the "C:\raylib\w64devkit\w64devkit.exe" program;
> 4. When the program opens, go to your orangeduck's Motion-Matching directory, (for example: "$ cd Documents/Motion-Matching") then type "$ make all"
> 5. The executable file of the project will be generated as "controller.exe", just open it.
> 
> And there you go :)

Thanks a lot！！

**Comment by ThrillDaWill** [comment]
> 

I'm a little confused about the RayGui repo. Mine doesn't include a file name "w64devkit". Is there a specific Repo or just the master one? Also, a video tutorial if possible would be super helpful to get started!

*Edit*: I was able to download w64devkit and run it in the raylib file but the command "$ cd Documents/Motion-Matching" gives me the error "can't cd to Documents/Motion-Matching: No such file directory."  (The file is in Documents and named properly) Any help would be appreciated!

**Comment by zhawhjw** [comment]
> 

It's bit late but you need to 'cd' to the proper disk at first,  i guess. Say, you place this repo at "D:/Motion-Matching", then you need to go to disk C at first.

**Comment by zhawhjw** [comment]
> _Edit_: I was able to download w64devkit and run it in the raylib file but the command "$ cd Documents/Motion-Matching" gives me the error "can't cd to Documents/Motion-Matching: No such file directory." (The file is in Documents and named properly) Any help would be appreciated!

It's bit late but you need to 'cd' to the proper disk at first, i guess. Say, you place this repo at "D:/Motion-Matching", then you need to go to disk C at first.

**Comment by pau1o-hs** [comment]
> > _Edit_: I was able to download w64devkit and run it in the raylib file but the command "$ cd Documents/Motion-Matching" gives me the error "can't cd to Documents/Motion-Matching: No such file directory." (The file is in Documents and named properly) Any help would be appreciated!
> 
> It's bit late but you need to 'cd' to the proper disk at first, i guess. Say, you place this repo at "D:/Motion-Matching", then you need to go to disk C at first.

He reached me out on LinkedIn for help, he was using that "OneDrive" directory instead of the real "C:\" you know hahaha. 

We should have marked here with some "Solved", sorry.

**Comment by orangeduck** [comment]
Thanks for helping resolve this.
