### ISSUE TITLE
Question about inertialize_pose_update

### ISSUE THREAD

**Issue by Bin-Ji** [orangeduck/Motion-Matching#20]
Hi, thanks for your great work, it really helps me a lot.
I have some questions about ```inertialize_pose_update``` in the ```controller.cpp```. First, I am confused with the terms of ```world space``` and ```space of the currently playing animation``` in ```line 447-450```. And I don't know how to get more information about inertialization.

**Comment by orangeduck** [comment]
Hi,

You might be able to find some more info about inertialization on my blog where I discuss it in a few articles:

https://theorangeduck.com/page/spring-roll-call#inertialization
https://theorangeduck.com/page/creating-looping-animations-motion-capture

Thanks,

Dan

**Comment by Bin-Ji** [comment]
Thank you very much for your timely reply.
