### ISSUE TITLE
How to modify simulation bone?

### ISSUE THREAD

**Issue by huang-1030** [orangeduck/Motion-Matching#22]
Thank you for sharing. 

When I add terrain information, the part of generating simulation bone in generate_database.py seems to be unavailable. In practice, it cannot generate the added Root node on the terrain, but drag the whole thing back to the plane. In this case, how should I modify this part so that the generated simulation bone can be on the fitted terrain.

**Comment by Onb209** [comment]
Would you mind sharing how you resolved this issue?
