### ISSUE TITLE
Shuttle running along X axis produces offsets along Y axis

### ISSUE THREAD

**Issue by hwx0000** [orangeduck/Motion-Matching#24]
Here is the problem, if I just use my left stick to make my character move along one X axis(like i just make him move to left or right), eventually the character will have offsets along another Y axis, which is really not the resul I want. I wonder if there are ways to prevent this from happing? Thanks in advance ::)

**Comment by orangeduck** [comment]
Hi Toby,

In this case you probably need to apply some adjustment to the produced animation like discussed in this article to force the movement along the desired axis: https://theorangeduck.com/page/code-vs-data-driven-displacement

Thanks,

Dan

**Comment by hwx0000** [comment]
Sorry, I should make it clear, this is not about animation, it's simply about Simulation Object, when you use gamepad to simply go left or right, the Simulation Object will have offsets in the other direction :(

**Comment by hwx0000** [comment]
I'm thinking about delaying the position  change for the Simulation Object, after it is well rotated, then use spring damper to change velocity and make movement for it
