### ISSUE TITLE
Question about the Database.bin

### ISSUE THREAD

**Issue by CatOnly** [orangeduck/Motion-Matching#28]
What's the list of animations store in `database.bin`  originally ?  It's just the same as Files in Files to Process's list ?
I know that this neural network compresses the animation data tremendously. And in general, we compresses animation data with Catmull-Rom. 
I'm just about to test which one compresses more data.

**Comment by orangeduck** [comment]
Yes. You could add more data from the lafan dataset and regenerate the database file if you wanted to see how it works with more data. There are more takes of running, jogging and walking from other subjects in the database you could try.

**Comment by CatOnly** [comment]
_With a few frames from only three files, I can have such smooth action_ !?
Oh my GOD !!
It seems that the compression rate of this should not be compared to that specific file, but to see the effect.

**I'm so appreciative of your work.**
