### ISSUE TITLE
Hi, bro, how to build feature.bin?

### ISSUE THREAD

**Issue by youngyangk** [orangeduck/Motion-Matching#3]
how to build feature.bin?
Thanks! your project is very important to me!

**Comment by orangeduck** [comment]
It is created at start-up when you run the demo as mentioned in the README:

https://github.com/orangeduck/Motion-Matching/blob/main/controller.cpp#L1280

**Comment by youngyangk** [comment]
Thanks! We don't have python code to build features, right? I'll analyze your cpp code, Thanks again!

**Comment by orangeduck** [comment]
No problem! And no, right now it must be built on the C++ side.

**Comment by youngyangk** [comment]
Hi, bro, I read your c++ code about building feature.bin carefully. Your code load datavase.bin to build feature.bin. By I konw, the database.bin is built by generate_database.py which contains the global position and volecity of the bones, I found in the database.h file, the funtion [compute_bone_position_feature ](https://github.com/orangeduck/Motion-Matching/blob/main/database.h#L382) apply [forward kinematics process](https://github.com/orangeduck/Motion-Matching/blob/main/database.h#L389) again. As the database.bin is ready global but local. why do we need KF based on database.bin data? Wish your reply. Best regards!

**Comment by orangeduck** [comment]
`database.bin` actually contains local joint positions/velocities, so that answers your question!

**Comment by youngyangk** [comment]
Thank you! But I found the value ‘leftfoot postion’  in the feature.bin does not exist in database.bin.  Feature.bin is a subset of database.bin, isn't it?  Sorry to disturb you, but this project matters a lot to me! Thanks for your help.  T^T

**Comment by orangeduck** [comment]
No it isn't a subset. It contains the matching features - in this case these features are the character space foot positions and velocities, hip velocity, and the trajectory positions and facing directions. None of these are in the database because the database contains local joint positions, and the root position (but not trajectory). These are computed from the database but are not a subset of what is in the database. You should read the paper and blog post carefully because I think they will answer most of your questions:

https://theorangeduck.com/media/uploads/other_stuff/Learned_Motion_Matching.pdf
https://montreal.ubisoft.com/en/introducing-learned-motion-matching/

**Comment by youngyangk** [comment]
Thank you for your kind reply.
Sorry, I did not express myself accurately. I mean in the current frame,  the positions, rotations data of the foot and hip joint in the feature.bin should exist in the database.bin, but I find not. Of course, the trajectory data of future frames need to be calculated. And are the feature.bin and database.bin in your project a data pair? Maybe, they are not paired data, so the foot positon value in the frature.bin is not equal to the database.bin.

**Comment by orangeduck** [comment]
The feature database `feature.bin` does not contain anything that is also in `database.bin`. The `database.bin` contains the local joint positions, rotations, velocities and angular velocities of all the joints. The `feature.bin` contains the character space positions and velocities of the feet joints (computed with FK) as well as the character space velocity of the hip joint and the trajectory data. They are not paired.

**Comment by youngyangk** [comment]
You are so kind!

**Comment by youngyangk** [comment]
Hi, Holden, how do you address the transition between gaits, for example walking to jumping? 
If you give walking gait vector [1, 0, 0, ...] and jumping [0, 1, 0, ...]. Do we need and how to label walking-jumping-transition?

**Comment by orangeduck** [comment]
It's up to you. If you want there to always explicitly be a transition of some form you need to label it as a separate gait.
