### ISSUE TITLE
How to build custom "character.bin" ?

### ISSUE THREAD

**Issue by wangshub** [orangeduck/Motion-Matching#8]
@orangeduck Thanks for your cool work ! 
- I want to make the character looks more like a humanoid robot, how can I change the `character.bin` ? 
- Are there any recommended editing tools ?

**Comment by orangeduck** [comment]
I generated this file by writing some python scripts in maya to export the mesh data. I don't think there will be any easy tools - probably you will need to write something custom, sorry!

**Comment by pau1o-hs** [comment]
Hi Holden! I'm trying to "write something custom" here. But I'm not really understanding:
```character_data.bone_weights```
```character_data.bone_indices```

I think I know what they are, but can't understand why they are matrices with 4 columns

Edit: Can you provide the character.fbx file? It'd help me making the reverse engineering of what you did to make the .bin hahaha

**Comment by wangshub** [comment]
> Hi Holden! I'm trying to "write something custom" here. But I'm not really understanding: `character_data.bone_weights` `character_data.bone_indices`
> 
> I think I know what they are, but can't understand why they are matrices with 4 columns
> 
> Edit: Can you provide the character.fbx file? It'd help me making the reverse engineering of what you did to make the .bin hahaha

@orangeduck

**Comment by orangeduck** [comment]
These are the bone weights and indices used in the linear blend skinning of the character.

**Comment by pau1o-hs** [comment]
Ok @orangeduck, just to check if I got it correctly. I have **n** vertices, for each one of them I get the 4 more relevant ```bone weights``` and the respective ```bone indices```, is that it?

If so, what happens if my vertex has less than 4 bone influences?

**Comment by pau1o-hs** [comment]
Hey @wangshub, I was able to build the character.bin, just uploaded it: https://github.com/pau1o-hs/Fbx2Bin;

I was working on the database.bin, but I'm without much free time by now, so if you want to continue from there...
